# 服务器端口
server:
  port: 8888

# Spring Boot 的数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.128.129:3306/fouo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  redis:
    database: 0
    host: 192.168.128.129
    port: 6379
    password:
    pool:
      max-active: 200
      max-idle: 10
      max-wait: -1
      min-idle: 0
    timeout: 1000